Repository kakaobrain/kogpt, pull requests merged in 2021-11, with the labels that each got.

#4 Web Demo Huggingface Spaces
  README.md
Labels: documentation, enhancement

#7 Fix typo in README.md
  README.md
  huggingface/KoGPT6B-ryan1.5b/README.md
Labels: documentation

#11 Update inference.py
  kogpt/inference.py
Labels: bug

#10 0 or negative temperature exception handling
  kogpt/__main__.py
Labels: enhancement
